version: 'lastest'
services:
  datascience:
    image: jupyter/datascience-notebook
    environment:
      - JUPYTER_TOKEN=password
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: datascience
